In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:90% !important;}</style>"))

In [2]:
from IPython.display import Image

# 8. 텍스트 분석


####  NLP 와 텍스트 분석

 - NLP : 인간의 언어를 이해하고 해석하는데 더 중점을 두고 기술이 발전해 옴

 - 텍스트분석 : 머신러닝, 언어이해, 통계 등을 활용해 모델을 수립하고 정보를 추출해 비즈니스 인텔리전스(Business Intelligence) 나 예측 분석 등의 분석 작업을 주로 수행

#### 텍스트 분석

- 텍스트분류 (text Classification)

 문서가 특정 분류 또는 카테고리에 속하는 것을 예측하는 기법을 통칭 합니다. 예를 들어 특정 신문기사 내용이 연애/정치/사회/문화 중 어떤 카테고리에 속하는지 자동으로 분류하거나 스팸 메일 검출 같은 프로그램이 이에 속합니다. 지도학습을 적용합니다. 


- 감성 분석 (sentiment Analysis)

     텍스트 에서 나타나는 감정/판단/믿음/의견/기분 등의 주관적인 요소를 분석하는 기법을 총칭합니다. 소셜미디어 감정분석, 영화나 제품에 대한 긍정 또는 리뷰, 여론조사 의견 분석 등의 다양한 영역에서 활용됩니다. Text Analytics 에서 가장 활발하게 사용되고 있는 분야 입니다. 지도학습 방법 뿐만 아니라 비지도 학습을 이용해 적용할 수 있습니다.  

- 텍스트요약 (Summarization)

  텍스트 내에서 중요한 주제나 중심 사상으 ㄹ추출하는 기법을 말합니다. 대표적으로 토픽 모델링 (Topic Modeling) 이 있습니다.

- 텍스트 군집화 (Clustering) 와 유사도 측정

  비슷한 유형의 문서에 대해 군집화를 수행하는 기법을 말합니다. 텍스트 분류를 비지도 학습으로 수행하는 방법의 일환으로 사용될 수 있습니다. 유사도 측정 역시 문서들간의 유사도를 측정해 비슷한 문서기리 모을 수 있는 방법입니다. 

## 8.1 텍스트 분석 이해  

### 텍스트 분석 수행 프로세스 

 1. 텍스트 사전 준비작업 (텍스트 전처리)
 
    텍스트를 피처로 만들기 전에 미리 클렌징, 대/소문자 변경, 특수문자 삭제 등의 클렌징 작업, 단어(Word) 등의 토큰화 작업 , 의미없는 단어 (Stop Word) 제거 작업, 어근추출 (Stemming /Lemmiatization) 등의 텍스트 정규화 작업을 수행하는 것을 통칭합니다.  

2. 피처 벡터화/추출

   사전 준비 작업으로 가공된 텍스트에서 피처를 추출하고 여기에 벡터값을 할당합니다. 대표적인 방법은 BOW 와 Word2Vec 이 있으며, BOW 는 대표적으로 Count 기반과 TF-IDF 기반 벡터화가 있습니다. 

3. ML 모델 수립 및 학습/예측/평가 

   피처 벡터화된 데이터 세트에 ML 모델을 적용해 학습/예측 및 평가를 수행 합니다. 

![](텍스트분석프로세스.png)

### 파이썬 기반의 NLP , 텍스트 분석 패키지

![](nltk.png)

- NLTK (Natural Language Toolkit for Python)

  파이썬의 기징 대표적인 NLP 패키지 입니다. 방대한 데이터 세트와 서브 모듈을 가지고 있으며 NLP의 거의 모든 영역을 커버하고 있습니다. 많은 NLP 패키지가 NLTK 의 영향을 받아 작성되고 있습니다. 
  수행속도 측면에서 아쉬운 부분이 있어서 실제 대량의 데이터 기반에서는 제대로 활용되지 못하고 있습니다.

- Gensim

  토픽 모델링 분야에서 가장 두각을 나타내는 패키지 입니다. 오래전부터 토픽 모델링을 쉽게 구현할 수 있는 기능을 제공해 왔으며, Word2Vec 구현 등의 다양한 신기능도 제공합니다. SpaCy 와 함께 가장 많이 사용되는 NLP 패키지 입니다.

- SpaCy 

  뛰어난 수행 성능으로 최근 가장 주목을 받는 NLP 입니다. 많은 NLP 애플리케이션에서 SpaCy 를 사용하는 사례가 늘고 있습니다. 

## 8.2 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

### 클렌징 

  텍스트 에서 분석에 오히려 방해가 되는 불필요한 문자, 기호 등을 사전에 제거하는 작업입니다. 
  예를 들어 HTML, XML 태그나 특정 기호 등을 사전에 제거합니다. 

### 텍스트 토큰화 

  문장 토큰화, 단어 토큰화, n-gram

####  문장 토큰화 (sent_tokenize)

마침표 , 개행문자 등 문장의 마지막을 뜻하는 기호에 따라 분리 

In [3]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/kwangsikyoo/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


#### 단어 토큰화 (word_tikenize)

문장을 단어로 토큰화. 기본적으로 공백 , 콤마 , 마침표, 개행문자 등으로 단어를 분리하지만, 정규 표현식을 이용해 다양한 유형으로 토큰화 수행 가능

In [4]:
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


- 문장 토큰화, 단어 토큰화 순차 수행

In [5]:
from nltk import word_tokenize, sent_tokenize

#여러개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화 만드는 함수 생성
def tokenize_text(text):
    
    # 문장별로 분리 토큰
    sentences = sent_tokenize(text)
    # 분리된 문장별 단어 토큰화
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

#여러 문장들에 대해 문장별 단어 토큰화 수행. 
word_tokens = tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


#### N-gram

문장을 개별 단어 별로 하나씩 토큰화 할 경우 문맥적인 의미는 무시될 수 밖에 없어 이러한 문제를 조금이라도 해결해 보고자 도입됨

N-Gram 은 연속된 n개의 단어를 하나의 토큰화 단위로 분리해 내는 것입니다. 

Agent Smith knocks the door 를 2-gram(bigram) 으로 만들면 
(Agent, Smith), (Smith, knocks), (knocks, the), (the, door) 와 같이 연속적으로 2개의 단어들을 순차적으로 이동하면서 단어들을 토큰화 합니다. 

### Stopwords 제거

스톱워드(Stop Word)는 분석에 큰 의미가 없는 단어를 지칭함. 
NLTK 에서 스톱 워드를 언어별로 목록화 하여 제공

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kwangsikyoo/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
print('영어 stop words 갯수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 갯수: 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [10]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
# 위 예제의 3개의 문장별로 얻은 word_tokens list 에 대해 stop word 제거 Loop
for sentence in word_tokens:
    filtered_words=[]
    # 개별 문장별로 tokenize된 sentence list에 대해 stop word 제거 Loop
    for word in sentence:
        #소문자로 모두 변환합니다. 
        word = word.lower()
        # tokenize 된 개별 word가 stop words 들의 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)
    
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


### Stemming과 Lemmatization

문법적 또는 의미적으로 변화하는 단어의 원형을 찾는 기능

- Stemmer 

  단순 변화형인 Work 는 정상적으로 원형을 추출하지만, amuse, hapopy , fancy 등 변형이 일어다는 닺어는 원형단어에서 철자가 어긋단 다른 단어로 인식하는 경우가 발생함

In [9]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


- Lemmatization 

  정확한 원형 단어 추출을 위하여 품사를 입력해 주어야 하며, 그만큼 정확하게 원형 단어를 추출해 줌

In [11]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kwangsikyoo/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


amuse amuse amuse
happy happy
fancy fancy


## 8.3 Bag of Words – BOW

![](bow.png)

문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도값을 부여해 피처 값을 추출하는 모델
모든 단어를 봉투(Bag) 에 넣어 흔든다는 개념으로 Bag of Words (BOW) 모델이라고 지칭

![](bow2.png)

- 장점 
 
  쉽고 빠르게 구축할 수 있으며, 예상보다 문서의 특징을 잘 나타낼 수 있는 모델이어서 전통적으로 여러 분야에서 활용도가 높습니다. 

- 단점

  문맥의미 반영 부족 : 단어의 순서를 고려하지 않아 문맥의미가 무시됨. 이를 보완 하기 위해 n-gram 활용
  
  희소행렬 문제 : BOW로 피처 백터화를 수행하면 희소 행렬 형태의 데이터 세트가 만들어 지기 쉬움. (많은 문서에서 단어를 추출하기 때문에 대부분의 데이터가 0 으로 채워지게 됨)
  

  
  

####  BOW 피처 벡터화

 머신러닝 알고리즘은 숫자형 데이터를 입력받아 작동하기 때문에 텍스트 데이터를 바로 사용할 수 없으므로 텍스트를 특정 의미를 가지는 숫자형 값인 벡터 값으로 변환해야 하는데 이를 피쳐 벡터화 라고 합니다. 
 

  ![](bow3.png)



- 카운트 기반의 벡터화

  단어 피처에 값을 부여할 때 해당 단어가 나타나는 횟수 (Count)를 붕하는 경우를 카운트 벡터화 라고 합니다. 
  카운트가 높을수록 중요한 단어로 인식 됩니다. 
  
  

- TF-IDF (Term Frequency Inverse Document Frequency) 기반의 벡터화

  개별 문서에서 주로 나타나는 단어에 높은 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어에 대해서는 패널티를 주는 방식으로 값을 부여
  ![](tfidf2.png)

### 희소 행렬 - COO 형식

![](coo.png)

COO(Coordinate:좌표) 형식은 0이 아닌 데이터만 별도의 데이터 배열 (Array)에 저장하고, 그 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장하는 방식

In [14]:
import numpy as np

dense = np.array( [ [ 3, 0, 1 ], [0, 2, 0 ] ] )

In [15]:
from scipy import sparse

# 0 이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

In [16]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

### 희소 행렬 – CSR 형식

![](csr.png)

CSR(Compressed Sparse Row) 형식은 COO 형식이 행과 열의 위치를 나타내기 위해서 반복적인 위치 데이터를 사용해야 하는 문제점을 해결한 방식 입니다

In [18]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

# 0 이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환 
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())


COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [19]:
dense3 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)