<h1>넘파이 ndarray 개요</h1>

In [225]:
import numpy as np

In [271]:
array1 = np.array([1,2,3])

print('array1 type', type(array1))
print('array1 array 형태', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('\narray2 type:', type(array2))
print('array2 array 형태', array2.shape)

array3 = np.array([[1,2,3]])
print('\narray3 type:', type(array3))
print('array3 array 형태', array3.shape)

print('\narray1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type <class 'numpy.ndarray'>
array1 array 형태 (3,)

array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)

array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)

array1: 1차원, array2: 2차원, array3:  2차원


<h1>ndarray 의 데이터 타입</h1>

In [19]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [23]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


<h1>ndarray 편리하게 생성하기</h1>

In [280]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [279]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [35]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [282]:
# rg = np.random.default_rng(1)
# rg

# a = rg.random((2,3))
# a

<h1>ndarray 의 차원과 크기를 변경하는 reshape()</h1>

In [284]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('\n array2:\n', array2)

array3 = array1.reshape(5,2)
print('\n array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]

 array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

 array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [227]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('\n array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print('\n array4 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]

 array2 shape: (2, 5)

 array4 shape: (5, 2)


In [288]:
array1 = np.arange(8)
print(array1)

array3d = array1.reshape((2,2,2))
print('\narray3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('\narray5:\n', array5.tolist())
print('array5 shape', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('\narray6:\n', array6.tolist())
print('array6 shape', array6.shape)

[0 1 2 3 4 5 6 7]

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


<h1>넘파이의 ndarray 의 데이터  세트 선택하기</h1>

In [292]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값 의미
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [67]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [83]:
#다차원 ndarray에서 단일 값 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('\n (row=0, col=0) index 가리키는 값', array2d[0,0])
print('\n (row=0, col=1) index 가리키는 값', array2d[0,1])
print('\n (row=1, col=0) index 가리키는 값', array2d[1,0])
print('\n (row=2, col=2) index 가리키는 값', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 (row=0, col=0) index 가리키는 값 1

 (row=0, col=1) index 가리키는 값 2

 (row=1, col=0) index 가리키는 값 4

 (row=2, col=2) index 가리키는 값 9


<h2>Slicing</h2>

In [299]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [88]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


<h3>2차원 배열에서의 Slicing</h3>

In [293]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array3d:\n', array2d)

print('\narray2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('\narray2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('\narray2d[1:3, :] \n', array2d[1:3, :])
print('\narray2d[:, :] \n', array2d[:, :])
print('\narray2d[:2, 1:] \n', array2d[:2, 1:])
print('\narray2d[:2, 0] \n', array2d[:2, 0])

array3d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]

array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]

array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[:2, 1:] 
 [[2 3]
 [5 6]]

array2d[:2, 0] 
 [1 4]


In [103]:
#2차원 ndarray 에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0].shape: ', array2d[0].shape, '\narray2d[1].shape: ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0].shape:  (3,) 
array2d[1].shape:  (3,)


### Fancy Indexing

In [241]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d, '\n')

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [298]:
array6 = array2d[[1,1] , [0,2]]
print('array2d[[0,1], [0,2]] =>', array6.tolist())


array2d[[0,1], [0,2]] => [4, 6]


### Boolean Indexing

In [117]:
#조건 필터링 + 검색

array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d > 5 인덱싱 결과', array3)

array1d > 5 인덱싱 결과 [6 7 8 9]


In [118]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('boolean 인덱스로 필터링 결과:', array3)

boolean 인덱스로 필터링 결과: [6 7 8 9]


In [120]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과: ', array4)

일반 인덱스로 필터링 결과:  [6 7 8 9]


In [270]:
#more
five_up = (array1d > 5)
print(array1d[five_up])

c = array1d[(array1d > 5) & (array1d < 8)]
print(c)

[6 7 8 9]
[6 7]


# 행렬의 정렬 - sort() 와 argsort()

### sort()

In [132]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort() 로 정렬
sort_array1 = np.sort(org_array)

print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)


#ndarray.sort() 로 정렬
sort_array2 = org_array.sort()

print('\norg_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

#내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('\n내림차순으로 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]

내림차순으로 정렬: [9 5 3 1]


In [139]:
array2d = np.array([[8,12], [7,1]])
print('array2d:\n', array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('\nrow 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('\ncolumn 방향으로 정렬:\n', sort_array2d_axis1)

array2d:
 [[ 8 12]
 [ 7  1]]

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]

column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스 반환 argsort()

In [209]:
#오름차순
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('오름차순 행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

#내림차순
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)[::-1]
print('\n내림차순 행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
오름차순 행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]

내림차순 행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [215]:
#argsort 사용 예시

#이름
names = np.array(['학생A', '학생B', '학생C', '학생D', '학생E'])

#점수
score = np.array([30,88,70,80,100])

#점수 내림차순 정렬
score_sort = np.sort(score)[::-1]
print('\n점수 내림차순', score_sort)

#내림차순 정렬한 점수의 index
score_argsort = np.argsort(score)[::-1]
print('\n내림차순 정렬한 점수의 index', score_argsort)

print('\n시험 성적 결과 - 국어 성적 내림차순')
print(score[score_argsort])
print(names[score_argsort])


점수 내림차순 [100  88  80  70  30]

내림차순 정렬한 점수의 index [4 1 3 2 0]

시험 성적 결과 - 국어 성적 내림차순
[100  88  80  70  30]
['학생E' '학생B' '학생D' '학생C' '학생A']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적 (행렬 곱)

In [205]:
#조건 : 왼쪽 행렬의 열 개수 = 오른쪽 행렬의 행 개수

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

In [208]:
A = np.array([[1,2],
              [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬\n', transpose_mat)

A의 전치 행렬
 [[1 3]
 [2 4]]
